# Generated by Django 5.2.14 on 2026-05-21 07:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business')], default='PERSONAL', max_length=10),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('business_registration_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{6,20}$')])),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='banking.account')),
            ],
        ),
    ]
