# Generated by Django 5.2.14 on 2026-05-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_biller_bill_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biller',
            name='name',
            field=models.CharField(choices=[('ELECTRICITY', 'Electricity'), ('WATER_UTILITIES', 'Water & Utilities'), ('INTERNET_BROADBAND', 'Internet & Broadband'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TOWN_COUNCIL', 'Town Council / Maintenance')], max_length=50),
        ),
    ]
