# Generated by Django 5.2.14 on 2026-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_biller_name_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biller',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='biller',
            unique_together={('account', 'name', 'reference')},
        ),
    ]
